# +PATCH,//UNDUMAG/SHELL
# +DECK,undumag_clean,T=SHELL.

rm -f undumag_facets.fct.bck 2>/dev/null
mv undumag_facets.fct undumag_facets.fct.bck 2>/dev/null
rm -f undumag_voxels.geo.bck 2>/dev/null
mv undumag_voxels.geo undumag_voxels.geo.bck 2>/dev/null

rm -f undumag.wrl.bck 2>/dev/null
mv undumag.wrl undumag.wrl.bck 2>/dev/null
rm -f undumag_mother_magnets.lis.bck 2>/dev/null
mv undumag_mother_magnets.lis undumag_mother_magnets.lis.bck 2>/dev/null
rm -f undumag_magnets.lis.bck 2>/dev/null
mv undumag_magnets.lis undumag_magnets.lis.bck 2>/dev/null
rm -f undumag.geo.bck 2>/dev/null
mv undumag.geo undumag.geo.bck 2>/dev/null
rm -f undumag.fil.bck 2>/dev/null
mv undumag.fil undumag.fil.bck 2>/dev/null

rm -f undumag.eps.bck 2>/dev/null
mv undumag.eps undumag.eps.bck 2>/dev/null
rm -f undumag.eps.bck 2>/dev/null
mv undumag.eps undumag.eps.bck 2>/dev/null
rm -f undumag_on-axis_dipoles.dat.bck 2>/dev/null
mv undumag_on-axis_dipoles.dat undumag_on-axis_dipoles.dat.bck 2>/dev/null
rm -f undumag_mh_rec.eps.bck 2>/dev/null
mv undumag_mh_rec.eps undumag_mh_rec.eps.bck 2>/dev/null
rm -f undumag_mh_iron.eps.bck 2>/dev/null
mv undumag_mh_iron.eps undumag_mh_iron.eps.bck 2>/dev/null
rm -f undumag_spectrum.eps.bck 2>/dev/null
mv undumag_spectrum.eps undumag_spectrum.eps.bck 2>/dev/null
rm -f undumag_field_profile.eps.bck 2>/dev/null
mv undumag_field_profile.eps undumag_field_profile.eps.bck 2>/dev/null
rm -f undumag_beff.eps.bck 2>/dev/null
mv undumag_beff.eps undumag_beff.eps.bck 2>/dev/null
rm -f undumag_on-axis_by_bz.eps.bck 2>/dev/null
mv undumag_on-axis_by_bz.eps undumag_on-axis_by_bz.eps.bck 2>/dev/null
rm -f undumag_on-axis_byint2_bzint2.eps.bck 2>/dev/null
mv undumag_on-axis_byint2_bzint2.eps undumag_on-axis_byint2_bzint2.eps.bck 2>/dev/null
rm -f undumag_on-axis_byint_bzint.eps.bck 2>/dev/null
mv undumag_on-axis_byint_bzint.eps undumag_on-axis_byint_bzint.eps.bck 2>/dev/null
rm -f undumag_trajectory.eps.bck 2>/dev/null
mv undumag_trajectory.eps undumag_trajectory.eps.bck 2>/dev/null

rm -f undumag.pdf.bck 2>/dev/null
mv undumag.pdf undumag.pdf.bck 2>/dev/null
rm -f undumag.pdf.bck 2>/dev/null
mv undumag.pdf undumag.pdf.bck 2>/dev/null
rm -f undumag_on-axis_dipoles.dat.bck 2>/dev/null
mv undumag_on-axis_dipoles.dat undumag_on-axis_dipoles.dat.bck 2>/dev/null
rm -f undumag_mh_rec.pdf.bck 2>/dev/null
mv undumag_mh_rec.pdf undumag_mh_rec.pdf.bck 2>/dev/null
rm -f undumag_mh_iron.pdf.bck 2>/dev/null
mv undumag_mh_iron.pdf undumag_mh_iron.pdf.bck 2>/dev/null
rm -f undumag_spectrum.pdf.bck 2>/dev/null
mv undumag_spectrum.pdf undumag_spectrum.pdf.bck 2>/dev/null
rm -f undumag_field_profile.eps.bck 2>/dev/null
mv undumag_field_profile.eps undumag_field_profile.eps.bck 2>/dev/null
rm -f undumag_beff.pdf.bck 2>/dev/null
mv undumag_beff.pdf undumag_beff.pdf.bck 2>/dev/null
rm -f undumag_on-axis_by_bz.pdf.bck 2>/dev/null
mv undumag_on-axis_by_bz.pdf undumag_on-axis_by_bz.pdf.bck 2>/dev/null
rm -f undumag_on-axis_byint2_bzint2.pdf.bck 2>/dev/null
mv undumag_on-axis_byint2_bzint2.pdf undumag_on-axis_byint2_bzint2.pdf.bck 2>/dev/null
rm -f undumag_on-axis_byint_bzint.pdf.bck 2>/dev/null
mv undumag_on-axis_byint_bzint.pdf undumag_on-axis_byint_bzint.pdf.bck 2>/dev/null
rm -f undumag_trajectory.pdf.bck 2>/dev/null
mv undumag_trajectory.pdf undumag_trajectory.pdf.bck 2>/dev/null

rm -f urad_stokes.dat.bck 2>/dev/null
mv urad_stokes.dat urad_stokes.dat.bck 2>/dev/null
rm -f urad_traxyz.dat.bck 2>/dev/null
mv urad_traxyz.dat urad_traxyz.dat.bck 2>/dev/null
rm -f undumag.pla.bck 2>/dev/null
mv undumag.pla undumag.pla.bck 2>/dev/null
rm -f undumag.pst.bck 2>/dev/null
mv undumag.pst undumag.pst.bck 2>/dev/null
rm -f undumag_matrix.pst.bck 2>/dev/null
mv undumag_matrix.pst undumag_matrix.pst.bck 2>/dev/null
rm -f undumag_field_profile.eps.bck 2>/dev/null
mv undumag_field_profile.eps undumag_field_profile.eps.bck 2>/dev/null
rm -f undumag_dipoles.beff.bck 2>/dev/null
mv undumag_dipoles.beff undumag_dipoles.beff.bck 2>/dev/null
rm -f undumag.beff.bck 2>/dev/null
mv undumag.beff undumag.beff.bck 2>/dev/null
rm -f undumag_bzeff.dat.bck 2>/dev/null
mv undumag_bzeff.dat undumag_bzeff.dat.bck 2>/dev/null
rm -f undumag_byeff.dat.bck 2>/dev/null
mv undumag_byeff.dat undumag_byeff.dat.bck 2>/dev/null
rm -f undumag_bzeff_dipoles.dat.bck 2>/dev/null
mv undumag_bzeff_dipoles.dat undumag_bzeff_dipoles.dat.bck 2>/dev/null
rm -f undumag_byeff_dipoles.dat.bck 2>/dev/null
mv undumag_byeff_dipoles.dat undumag_byeff_dipoles.dat.bck 2>/dev/null
rm -f undumag_integrals_int.map 2>/dev/null
mv undumag_integrals_int.map undumag_integrals_int.map.bck 2>/dev/null
rm -f undumag_integral.map 2>/dev/null
mv undumag_integral.map undumag_integral.map.bck 2>/dev/null
rm -f undumag.map 2>/dev/null
mv undumag.map undumag.map.bck 2>/dev/null
rm -f undumag_map.dip 2>/dev/null
mv undumag_map.dip undumag_map.dip.bck 2>/dev/null
rm -f undumag_on-axis_dipoles.dat.bck 2>/dev/null
mv undumag_on-axis_dipoles.dat undumag_on-axis_dipoles.dat.bck 2>/dev/null
rm -f undumag_on-axis.dat.bck 2>/dev/null
mv undumag_on-axis.dat undumag_on-axis.dat.bck 2>/dev/null
rm -f undumag.cnv.bck 2>/dev/null
mv undumag.cnv undumag.cnv.bck 2>/dev/null
rm -f undumag_force.fbx.bck 2>/dev/null
mv undumag_force.fbx undumag_force.fbx.bck 2>/dev/null
rm -f undumag.frc.bck 2>/dev/null
mv undumag.frc undumag.frc.bck 2>/dev/null
rm -f undumag.ver.bck 2>/dev/null
mv undumag.ver undumag.ver.bck 2>/dev/null
rm -f undumag.dfr.bck 2>/dev/null
mv undumag.dfr undumag.dfr.bck 2>/dev/null
rm -f undumag_integrals_inf.map.bck 2>/dev/null
mv undumag_integrals_inf.map undumag_integrals_inf.map.bck 2>/dev/null
rm -f undumag.sta.bck 2>/dev/null
mv undumag.sta undumag.sta.bck 2>/dev/null

rm -f undumag.mag
